image:https://api.travis-ci.org/spring-projects/spring-boot-data-geode.svg?branch=master["Build Status", link="https://travis-ci.org/spring-projects/spring-boot-data-geode"]

== Spring Test Framework for Apache Geode & Pivotal GemFire 

This project is a _Spring Data_ module building on the core _Spring Framework's_ `TestContext` used to
write _Unit_ and _Integration Tests_ for both _Spring Data_ for https://pivotal.io/pivotal-gemfire[Pivotal GemFire]
as well as _Spring Data_ for https://geode.apache.org/[Apache Geode].

This project was born from https://projects.spring.io/spring-data-gemfire/[_Spring Data for Pivotal GemFire's_]
(https://github.com/spring-projects/spring-data-gemfire[GitHub project])
https://github.com/spring-projects/spring-data-gemfire/tree/2.0.6.RELEASE/src/test/java/org/springframework/data/gemfire/test[test framework].
This _test framework_ is used in SDG's test suite to test the proper function of Apache Geode or Pivotal GemFire
when used in a _Spring_ context.

For many years, users have asked for a way to test their Apache Geode or Pivotal GemFire-based, _Spring_ applications,
whether writing _Unit_ or _Integrations_ tests.  This project is the answer.

This **new** project is still under development and will have documentation and examples, soon.
